load("@rules_cc//cc:cc_binary.bzl", "cc_binary")
load("//bazel:dist.bzl", "linux_aarch64_dist", "linux_x86_64_dist", "macos_aarch64_dist")

package(default_visibility = ["//visibility:public"])

linux_x86_64_dist(
    name = "rocksdb-x86_64-unknown-linux-gnu",
    srcs = [":distribution_libraries"],
)

linux_aarch64_dist(
    name = "rocksdb-aarch64-unknown-linux-gnu",
    srcs = [":distribution_libraries"],
)

cc_binary(
    name = "rocksdb_smoke_test",
    srcs = ["tests/rocksdb_smoke_test.cc"],
    copts = ["-std=c++20"],
    deps = ["@rocksdb"],
)

linux_aarch64_dist(
    name = "rocksdb-smoke-aarch64-unknown-linux-gnu",
    srcs = [":rocksdb_smoke_test"],
)

linux_x86_64_dist(
    name = "rocksdb-smoke-x86_64-unknown-linux-gnu",
    srcs = [":rocksdb_smoke_test"],
)

macos_aarch64_dist(
    name = "rocksdb-aarch64-apple-darwin",
    srcs = [":distribution_libraries"],
)

macos_aarch64_dist(
    name = "rocksdb-smoke-aarch64-apple-darwin",
    srcs = [":rocksdb_smoke_test"],
)

filegroup(
    name = "dist",
    srcs = [
        ":rocksdb-aarch64-apple-darwin",
        ":rocksdb-aarch64-unknown-linux-gnu",
        ":rocksdb-x86_64-unknown-linux-gnu",
    ],
)

filegroup(
    name = "distribution_libraries",
    srcs = [
        "@bzip2//:bz2",
        "@lz4",
        "@lz4//:lz4_hc",
        "@rocksdb",
        "@snappy",
        "@zlib",
        "@zstd",
    ],
)
